# Generated by Django 5.0.4 on 2024-04-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piloto.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEstudante', models.CharField(max_length=100)),
                ('cpfEstudante', models.CharField(max_length=14, unique=True)),
                ('matriculaEstudante', models.CharField(max_length=9, unique=True)),
                ('dataAmoversarop', models.DateField()),
                ('eImagem', models.ImageField(upload_to='')),
                ('situacaoEstudante', models.CharField(choices=[(1, 'Vinculado'), (2, 'Formado'), (3, 'Jubilado'), (4, 'Evadido')], default='VINCULADO', max_length=10)),
                ('modoDeEntrada', models.CharField(choices=[(1, 'Vestibular'), (2, 'SISU'), (3, 'PSEnem')], default='SISU', max_length=10)),
                ('cursoEstudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piloto.cursos')),
            ],
        ),
    ]
