# Generated by Django 5.0.4 on 2024-04-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piloto.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('brith_date', models.DateField()),
                ('image', models.ImageField(upload_to='piloto/img/%Y/%m/%d/')),
                ('situation', models.CharField(choices=[('Vinculado', 'Vinculado'), ('Formado', 'Formado'), ('Jubilado', 'Jubilado'), ('Evadido', 'Evadido')], default='VINCULADO', max_length=10)),
                ('entry_mode', models.CharField(choices=[('Vestibular', 'Vestibular'), ('SISU', 'SISU'), ('PSEnem', 'PSEnem')], default='SISU', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piloto.courses')),
            ],
        ),
    ]
