# Generated by Django 5.0.4 on 2024-04-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0002_remove_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
